# Generated by Django 4.1.9 on 2023-07-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_two',
            field=models.EmailField(default=1, max_length=254, primary_key=True, serialize=False, verbose_name='доп_Почта'),
        ),
    ]
