# Generated by Django 4.1.9 on 2023-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_email_profile_email_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_two',
            field=models.EmailField(default=1, max_length=254, primary_key=True, serialize=False, verbose_name='Почта 2'),
        ),
    ]
