# Generated by Django 4.2.2 on 2023-06-27 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Координата',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='FilterPereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(verbose_name='url')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='public.level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pereval_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=10)),
                ('beautyTitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('other_titles', models.CharField(blank=True, max_length=100, null=True, verbose_name='Другое название')),
                ('connect', models.CharField(blank=True, max_length=100, null=True, verbose_name='Соединение')),
                ('file', models.FileField(blank=True, null=True, upload_to='pablic/', verbose_name='Фаил')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.coords', verbose_name='Координаты')),
                ('filters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.filterpereval', verbose_name='Фильтр')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery', verbose_name='Изображения')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.level', verbose_name='Сложность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Новое название',
                'verbose_name_plural': 'Новые названия',
            },
        ),
    ]
