# Generated by Django 4.1.9 on 2023-07-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public", "0002_alter_coords_height_alter_coords_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pereval_added",
            name="connect",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=10,
                null=True,
                verbose_name="Соединение",
            ),
        ),
    ]
